### ISSUE TITLE
vsftpd support

### ISSUE THREAD

**Issue by NuclearCookie** [dptechnics/DPT-Board-OS#3]
Hi,
I was trying to use the DPT-Board as a simple ftp server for my local network. How can I install a package like `vsftpd` for example? The software is not included in your opkg paths. 
Any advice? 
If it's an option to use standard OpenWRT that would also be nice, as I'm not really interested in the custom web interface. Some feedback would be appreciated. 
Thank you

**Comment by daanpape** [comment]
Hi Pieter,

Great to hear you are building an FTP-server. I strongly advise you to upgrade your DPT-Board OS to the latest version via the firmware update page. 

You will find there are now a multitude of FTP server packages compiled, also vsftpd:

http://firmware.dptechnics.com/dptv1/10/packages/packages/vsftpd_3.0.2-4.1_ar71xx.ipk

You can also install the LuCI webinterface, but although we have compiled it, we have not tested it and do not support it officially. 

Kind regards,
Daan

**Comment by NuclearCookie** [comment]
Daan,

If I follow your instructions on your website to upgrade the firmware https://www.dptechnics.com/guides/dpt-board/update-firmware it doesn't show version 10

![screenshot from 2017-03-19 18 04 31](https://cloud.githubusercontent.com/assets/5354914/24082983/dc7c5bd2-0cce-11e7-8d29-b9b7e9336219.png)

how can I get it?

**Comment by daanpape** [comment]
Hi Pieter,

There was indeed a bug in our OTA versioning file. I have now corrected the error, can you please retry?

Kind regards,
Daan

**Comment by NuclearCookie** [comment]
Yes, version 10 is now available! Sounds good :) I think I can continue from here. Thanks for the swift support!
